<template>
  <div class="admin-page"><div class="admin-heading"><div><p class="eyebrow">Área administrativa</p><h1>Criação para Vitrine</h1><p class="muted">Produtos publicados aparecem imediatamente no catálogo.</p></div><button class="button button-outline" type="button" @click="router.push('/')"><ArrowLeft :size="16" /> Ver vitrine</button></div><div class="admin-layout"><form class="admin-form" @submit.prevent="save"><div class="form-title"><h2>{{ editingId ? 'Editar produto' : 'Novo produto' }}</h2><button v-if="editingId" class="text-button" type="button" @click="reset">Cancelar edição</button></div><label>Nome do produto<input v-model.trim="form.title" required maxlength="120" /></label><label>Descrição<textarea v-model.trim="form.description" required maxlength="500"></textarea></label><div class="form-row"><label>Preço<input v-model.number="form.price" type="number" min="0" step="0.01" required /></label><label>Categoria<select v-model="form.category" required><option disabled value="">Escolha</option><option v-for="category in CATEGORIES" :key="category" :value="category">{{ categoryLabel(category) }}</option></select></label></div><label>Link do produto (opcional)<input v-model.trim="form.link" type="url" placeholder="https://..." /></label><div class="upload-grid"><ImageUpload v-for="slot in slots" :key="slot.key" :label="slot.label" :url="form[slot.key]" @uploaded="(url) => form[slot.key] = url" /></div><p v-if="formError" class="form-error" role="alert">{{ formError }}</p><button class="button button-dark full" type="submit" :disabled="saving">{{ saving ? 'Salvando...' : editingId ? 'Salvar alterações' : 'Publicar produto' }} <Check :size="16" /></button></form><section class="admin-list"><div class="list-heading"><h2>Produtos publicados</h2><button class="icon-button" type="button" title="Atualizar lista" aria-label="Atualizar lista" @click="load"><RefreshCw :size="17" :class="{ spin: loading }" /></button></div><div v-if="listError" class="state error-state">{{ listError }}</div><div v-else-if="loading" class="state"><LoaderCircle class="spin" :size="22" /></div><div v-else class="admin-products"><article v-for="product in products" :key="product.id" class="admin-product"><img :src="product.oneImageUrl || fallbackImage" :alt="product.title" /><div><strong>{{ product.title }}</strong><small>{{ categoryLabel(product.category) }} · {{ formatPrice(product.price) }}</small></div><div class="product-actions"><button class="icon-button" type="button" title="Editar" aria-label="Editar produto" @click="edit(product)"><Pencil :size="16" /></button><button class="icon-button danger" type="button" title="Excluir" aria-label="Excluir produto" @click="remove(product)"><Trash2 :size="16" /></button></div></article><p v-if="!products.length" class="muted">Nenhum produto publicado.</p></div></section></div></div>
</template>
<script setup lang="ts">
import { reactive, ref } from 'vue'; import { useRouter } from 'vue-router'; import { ArrowLeft, Check, LoaderCircle, Pencil, RefreshCw, Trash2 } from 'lucide-vue-next'; import chocolateImage from '../../chocolate.png'; import ImageUpload from './ImageUpload.vue'; import { CATEGORIES, type Category, type Product, type ProductPayload } from '../types'; import { messageFromError } from '../services/api'; import { productsService } from '../services/products';
const router = useRouter(); const products = ref<Product[]>([]); const loading = ref(false); const saving = ref(false); const listError = ref(''); const formError = ref(''); const editingId = ref<number | null>(null); const fallbackImage = chocolateImage; const slots = [{ key: 'oneImageUrl', label: 'Imagem principal' }, { key: 'twoImageUrl', label: 'Imagem 2 (opcional)' }, { key: 'threeImageUrl', label: 'Imagem 3 (opcional)' }] as const; const form = reactive<ProductPayload>({ title: '', description: '', price: 0, oneImageUrl: '', twoImageUrl: '', threeImageUrl: '', link: '', category: '' as Category });
function categoryLabel(category: Category) { return ({ Sliciecakes: 'Slice Cakes', DeliciasDePote: 'Delícias no pote', DatasEspeciais: 'Datas especiais' } as Record<string, string>)[category] || category; } function formatPrice(value: number) { return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number(value) || 0); }
async function load() { loading.value = true; listError.value = ''; try { products.value = await productsService.all(); } catch (reason) { listError.value = messageFromError(reason, 'Não foi possível carregar os produtos.'); } finally { loading.value = false; } }
function reset() { Object.assign(form, { title: '', description: '', price: 0, oneImageUrl: '', twoImageUrl: '', threeImageUrl: '', link: '', category: '' as Category }); editingId.value = null; formError.value = ''; }
function edit(product: Product) { Object.assign(form, product); editingId.value = product.id; window.scrollTo({ top: 0, behavior: 'smooth' }); }
async function save() { if (!form.title || !form.description || !form.oneImageUrl || !form.category || !form.link || form.price < 0) { formError.value = 'Preencha nome, descrição, preço, imagem principal, link e categoria.'; return; } saving.value = true; formError.value = ''; try { if (editingId.value) await productsService.update(editingId.value, form); else await productsService.create(form); await load(); reset(); } catch (reason) { formError.value = messageFromError(reason, 'Não foi possível salvar o produto.'); } finally { saving.value = false; } }
async function remove(product: Product) { if (!window.confirm(`Excluir “${product.title}”?`)) return; try { await productsService.remove(product.id); await load(); } catch (reason) { listError.value = messageFromError(reason, 'Não foi possível excluir o produto.'); } }
load();
</script>
